bharathgs/Awesome-pytorch-list

README.md
Multi-style transfer in real-time using a single network.
=> PyTorch Implementation of MSG-Net

README.md
https://arxiv.org/abs/1703.07332
=> Added face alignment paper, ICCV 2017

README.md
Pytorch implementations of various Deep NLP models in cs-224n(Stanford Univ: NLP with Deep Learning)
=> DeepNLP-models-Pytorch

README.md
Pytorch implementation of FlowNet 2.0: Evolution of Optical Flow Estimation with Deep Networks.
=> Add Pytorch implementation of FlowNet2

README.md
I think Allen NLP deserves to be in the set of NLP and Speech Processing toolkits.
=> Add Allen NLP library

README.md
Implemented following paper: NIMA: Neural Image Assessment https://arxiv.org/abs/1709.05424 with pre-trained and deploed model
=> add Neural-IMage-Assessment 2

README.md
Added Book on Pytorch from packt [Deep Learning with pytorch](https://www.amazon.in/Deep-Learning-PyTorch-practical-approach/dp/1788624335)
=> Adding book resource

README.md
Modular Deep Reinforcement Learning framework in PyTorch.
=> add SLM-Lab for reinforcement learning

README.md
Hi!
I thought this book title might be an excellent contribution to your list of PyTorch books and resources.
Please, let me know what you think about it.
Thank you for your consideration.
Rada.
=> adding to your list

README.md
Updated the forks badge to 600+
Removed unnecessary spaces for consistency across readme.
=> Update README.md badges and formatting

README.md
Tutorials and examples include Reinforcement Training, NLP, CV
=> add one Tutorial

README.md
Pytorch implementation of Google AI's 2018 BERT, with simple annotation
https://github.com/codertimo/BERT-pytorch
=> Add BERT-PyTorch

README.md
Hello there.
I've added a new (probably useful) item to the list.
=> Add a new item to the list.

README.md
Let me know if I need to change anything.
=> Added neural-style-pt

README.md
A paper from ICLR 2019 on graphs.
=> Added an ICLR 2019 paper implementation.

README.md
A Higher-Order Graph Convolutional Layer
=> Added a NeurIPS 2018 paper.

README.md
Adding my Rust bindings for PyTorch :)
=> Adding tch-rs.

README.md
=> Added CapsGNN

README.md
Semi-Supervised Graph Classification: A Hierarchical Graph Perspective
=> Added a WWW 19 paper.

README.md
Added a new paper, modified the repo name of an other that I added.
=> Added an ICML 2019 paper.

README.md
Add the kornia library to the CV section.
=> add kornia library

README.md
A PyTorch implementation of "Cluster-GCN: An Efficient Algorithm for Training Deep and Large Graph Convolutional Networks" (KDD 2019).
=> Added a KDD 19 paper.

README.md
CIFAR-ZOO  contains the pytorch code for multiple CNN architectures and improve methods based on the following papers, hope the implementation and results will helpful for your research!!
=> add CIFAR-ZOO 

README.md
Added adaptive segmentation mask attack (ASMA) from "Impact of Adversarial Examples on Deep Learning Models for Biomedical Image Segmentation", published at MICCAI 2019.
=> Added paper implementation

README.md
Add a PyTorch Implementation of the Paper: Unsupervised Video Interpolation Using Cycle Consistency. In ICCV 2019.
=> unsupervised video interpolation

README.md
https://github.com/jettify/pytorch-optimizer -- collections of modern optimization algorithms for PyTorch, includes: AccSGD, AdaBound, AdaMod, DiffGrad, Lamb, RAdam, RAdam, Yogi.
=> Add pytorch-optimizer to the list

README.md
Add [pytorch-cpp](https://github.com/prabhuomkar/pytorch-cpp) to tutorials section. 
**Description of the tutorial**:
C++ implementations of PyTorch tutorials for deep learning researchers (based on the Python tutorials from [pytorch-tutorial](https://github.com/yunjey/pytorch-tutorial)).
=> Add pytorch-cpp tutorial.

README.md
[MMDetection](https://github.com/open-mmlab/mmdetection) is an open source detection toolbox with 8.7k stars and 2.9k forks. It implements many state-of-the-art methods.
=> Add MMDetection

README.md
It's a tutorial series in the form of Jupyter notebooks.
https://jovian.ml/aakashns/collections/deep-learning-with-pytorch
=> Add "Deep Learning with PyTorch: Zero to GANs"

README.md
Thanks for the nice compilation of PyTorch resources! I've added FlashTorch and Lucent (disclaimer I am the owner of Lucent)
=> Add FlashTorch and Lucent

README.md
Link: https://github.com/bharathgs/Awesome-pytorch-list
PyTorch/XLA is a Python package that uses the XLA deep learning compiler to connect the PyTorch deep learning framework and Cloud TPUs. You can try it right now, for free, on a single Cloud TPU with Google Colab, and use it in production and on Cloud TPU Pods with Google Cloud.
=> Add PyTorch/XLA

README.md
Recently, [OpenMMLab](https://open-mmlab.github.io/) released several new codebases for computer vision research using PyTorch, including [MMDetection3D](https://github.com/open-mmlab/mmdetection3d), [MMEditing](https://github.com/open-mmlab/mmediting), [MMSegmentation](https://github.com/open-mmlab/mmsegmentation), [MMAction2](https://github.com/open-mmlab/mmaction2), [MMPose](https://github.com/open-mmlab/mmpose).
=> Add several open mmlab projects

README.md
add paper implementation in the area of GNN: Design Provably More Powerful GNNs for Structural Representation Learning
=> Update paper: Distance Encoding

README.md
Added https://github.com/lab-ml/nn to tutorials list.
=> Add LabML NN to tutorials list

README.md
Add Backprop library to NLP section.
=> Add Backprop

README.md
Flower is an agnostic federated learning framework and many PyTorch examples with Flower are existing already that we want to share with the PyTorch community:
- add Flower to the list of libraries
- add PyTorch: from centralized to federated to the list of tutorials
=> add federated learning examples

README.md
=> Added RoMa

README.md
Added Renate, a library for continual learning algorithms
=> Added Renate
